#指定端口号
server:
  port: 8761

# 指定应用程序名称
spring:
  application:
    name: springcloud-eureka-server


eureka:
  instance:
    hostname: localhost
  client:
    #下面两个false代表这是个服务端
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/