server:
  port: 8765

# 服务与服务之间相互调用一般都是根据这个name 。
spring:
  application:
    name: student-service-consumer

eureka:
  client:
    serviceUrl:
      # 指定服务注册中心的地址
      defaultZone: http://localhost:8761/eureka/

student-service-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule