server:
  port: 8763
  servlet:
    #工程路径名
    context-path: /student

spring:
  application:
    # 服务与服务之间相互调用一般都是根据这个name 。
    name: student-service-provider
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  #配置数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sc_test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      connection-init-sqls: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci

#mapper.xml 文件路径
mybatis:
  mapper-locations: classpath*:com/kuaibao/**/*Mapper.xml

eureka:
  client:
    serviceUrl:
      # 指定服务注册中心的地址
      defaultZone: http://localhost:8761/eureka/

#mybatis-plus 自动生成mapper配置
mybatis-plus:
  generator:
    driver: ${spring.datasource.driver-class-name}
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    parentPackage: com.kuaibao.module
    #从数据库要生成模板的表名,可支持多个表名,先不做
    table: student